version: '3'

services:
  db: # MYSQL
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: printerlynx
      MYSQL_ROOT_PASSWORD: PrinterlynxDev
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
    mysql-data:
    minio-data: