version: '3'

services:
  db: # MYSQL
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: printerlynx
      MYSQL_ROOT_PASSWORD: PrinterlynxDev
    volumes:
      - mysql-data:/var/lib/mysql
  rabbitmq: # RABBITMQ
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: printerlynx
      RABBITMQ_DEFAULT_PASS: PrinterlynxDev
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
  minio: # MINIO
    image: minio/minio
    ports:
      - "9090:9000"
      - "9001:9001"
    restart: always
    environment:
      MINIO_ROOT_USER: printerlynx
      MINIO_ROOT_PASSWORD: PrinterlynxDev
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"

volumes:
    mysql-data:
    rabbitmq-data:
    minio-data: